### ISSUE TITLE
Any idea on how to make this suitable for "user preferences"?

### ISSUE THREAD

**Issue by n3storm** [nitely/django-djconfig#12]
I would like to contribute (if possible) and make djconfig also useful for storing user preferences.

From what you created we must keep a key-value scheme, so adding a user field to Config model is not appropiate.

I was think in creating a Proxy model named UserConfig with a Manager that filters keys starting with "user_%userpk%" pattern. I am not sure how though because of the eternal separation between request and models.

There would be a {{userconfig.wathever}} variable added in context processor and middleware using request.user.pk to filter user config entries.

What do you think about this approach?

**Comment by nitely** [comment]
Hi,

The canonical way to store user preferences is to keep them in a profile
model (ie: a model with an OneToOneField related to the user model) as far
as I know.

This app is not meant to be used that way. All the [admin] preferences are
loaded in memory, storing preferences for every user (without an expiration
time) would kill your performance.

You'd use djConfig to store custom preferences that are usually stored in
settings.py.

2015-06-12 5:49 GMT-03:00 Néstor Díaz Valencia <notifications@github.com>:

**Comment by n3storm** [comment]
Hi Nitely,

This is an example of my scenario:
I have a ListView for records, that can switch between tables or plain list templates. Also number of records displayed/paginated, column sorting, etc.

There are default values managed by "normal" djconfig Config but user can override those values with my idea of djconfig UserConfig. There also some ideas for "workspace" or "team" config, etc.
I was thinking in adding an option to choose caching backend (I use redis myself)

Do you still think it will overkill?

**Comment by nitely** [comment]
Adding backend support to djConfig can backfire in many ways (ie: if the redis backend gets cleared while running the django/djconfig app) I don't even want to think about, that's why I removed the backend support in the first place, to keep things simple.

Extending the user model is the way to go, IMO.

DjConfig converts every setting to the right python type defined by the ConfigForm at the very first request to every server worker/process. It just can't be *easily* extended the way you want.

**Comment by n3storm** [comment]
I see, I have been naive about this... Thank you!
