### ISSUE TITLE
How to access config when testing apps within project

### ISSUE THREAD

**Issue by tylerecouture** [nitely/django-djconfig#31]
When I try to test an app within my project, it doesn't recognize any of the config attributes in my project.  For example, I get this error:
`AttributeError: Attribute "hs_active_semester" not found in config.`

I've tried adding `@override_djconfig(hs_active_semester="1")` to the test
without luck.

My project structure is:

```
my_project
 > forms.py  <-- djconfig form in there
 > apps.py <-- djconfig registered in there
 > etc
my_app1
 > models.py
 > views.py
 > tests.py <-- throws the error because it can't find config attributes it needs to do stuff
 > etc
```

**Comment by tylerecouture** [comment]
or, is there a way for me to save my config settings into a fixture to load it?

**Comment by nitely** [comment]
forms.py and apps.py must be in your app (each app), not within the project. That's likely the issue.

```
# from django tutorial
polls/
    __init__.py
    admin.py
    apps.py
    migrations/
        __init__.py
    models.py
    tests.py
    views.py
```

> or, is there a way for me to save my config settings into a fixture to load it?

Config settings will take the default value you have passed when instantiating the fields,  i.e `forms.CharField(initial="this is the initial string")`, then you should use `@override_djconfig(...)` to change the value.

**Comment by tylerecouture** [comment]
Thanks!  Any suggestions for how to handle common config settings that are required project wide?  Unfortunately, my apps are horribly interlinked.

**Comment by nitely** [comment]
Yes, add a `core` app that has those settings. Settings defined by some app are available to all apps.

**Comment by tylerecouture** [comment]
Thanks, but in my case `my_project` is also an app, and should be treated the same way as other apps, according to Django docs.  For example `my_project` is in the included apps.  So would seem odd to create a separate app for what my_project_ is already doing (i.e. acting as the `core` app)?

**Comment by nitely** [comment]
I didn't realized thath. It should work then. So, `my_app1.tests` raises an exception because it can't find a setting defined in `my_project.forms`? is that the case?

if you have a `hs_active_semester` field in that form, then the form is not getting registered. There should be something like this:

```python
class MyAppConfig(AppConfig):
    # stuff here...

    def ready(self):
        from .forms import MyConfigForm
        djconfig.register(MyConfigForm)
```

in that `my_project.apps`. Try adding a `print('foobar')` in that `ready` method to make sure it's being called.

**Comment by nitely** [comment]
ah, I know what it must be. The middleware must be called in order to load the settings. In other words, the settings are loaded the first time a request is served. Try adding a `djconfig.reload_maybe()` call after registering the form.

```python
import djconfig

class MyAppConfig(AppConfig):
    # stuff here...

    def ready(self):
        from .forms import MyConfigForm
        djconfig.register(MyConfigForm)
        djconfig.reload_maybe()
```

There is a warning in django's docs about not querying the database within the `ready` method, but it only mentions alter queries (save, delete, update), so I think this should be fine (`reload_maybe` does a get). Otherwise, you will have to add the call to the test `setUp` method.

**Comment by tylerecouture** [comment]
Thank you!  Adding `djconfig.reload_maybe()` to my test `setUp` method worked!

**Comment by nitely** [comment]
Awesome! I've add it to the usage docs. Thanks for reporting this!
